### ISSUE TITLE
.NET Core 3.0/3.1 support

### ISSUE THREAD

**Issue by niklasgransjoen** [dwmkerr/sharpgl#166]
Are there any plans to port this project to .NET Core 3.1? Seeing as .NET Framework is slowing down, and the future of the framework (.NET 5) is an extension of .NET Core 3.1, I think it's the logical move to do a port.

**Comment by dwmkerr** [comment]
In theory this should be pretty straightforward - the bulk of the code is DLL imports and, some simple classes to wrap GL objects and then Windows controls. All of this functionality is available in .NET Core 3.0 onwards.

As it's been a few years since I've been doing enterprise .NET, one question I would have is on compatibility - is this likely to cause issues with people who are already using the code in large .NET Framework-based codebases, or would they be able to add a .NET Core based dependency?

Even if the legacy issue remains, it would probably still make sense to make a new Major release targeting .NET Core, and then maintain a legacy release branch for anyone who needs .NET framework support.

WDYT?

**Comment by anhellwig** [comment]
You can target multiple frameworks in a csproj file when using the new SDK style. The resulting nuget package then contains .NET Core and traditional .NET Framework or .NET Standard assemblies. This way, you don't need to maintain separate code branches.

**Comment by dwmkerr** [comment]
OK I'm working on this now in a new branch, hopefully will have updates very soon!

**Comment by dwmkerr** [comment]
OK it's done! I've written up the experiences here 😄 

https://dwmkerr.com/modernising-dotnet-projects/

If anyone has any problems open up an issue and I'll look into them. Am planning to spend some time cleaning up the library a bit and looking at support for MacOS and Linux.
