### ISSUE TITLE
SharpGL.WinForms is using deprecated functions

### ISSUE THREAD

**Issue by barbossa404** [dwmkerr/sharpgl#36]
When I tried profiling my application, I noticed that glError() always returns GL_INVALID_OPERATION before the beginning of the rendering function.

The problem appears to be that the WinForms-Control creates and pushes a perspective matrix even when the Context is set to a higher version of OpenGL (e.g. 4.3.0) and therefore all fixed pipeline funtions are deprecated and cause errors.

I hope I did not miss any option which allows to change this behavior.

**Comment by dwmkerr** [comment]
Hi @barbossa404,

Looking into the code in more detail, it seems like actually the only time that the immediate mode functions will be called is when you don't provide your own SizeChanged handler for the OpenGL control. If you are using OpenGL 4.3, you should provide your own handler and ideally deal with resizing yourself (rather than relying on the default). If you rely on the default (which is fixed mode) the OpenGL errors are appropriate, because essentially they are telling you that you should use something custom to your project. Some people will prefer to have the errors even when using OpenGL 4.3 because they may well use the deprecated immediate mode APIs, in this case the default projection will serve them. Any thoughts on this?
